### ISSUE TITLE
React runtime does not include the Node standard library

### ISSUE THREAD

**Issue by zchandikaz** [Sphereon-Opensource/ssi-mobile-wallet#158]
![image](https://github.com/Sphereon-Opensource/ssi-mobile-wallet/assets/11471424/735aed6a-7d4f-45dc-969b-2d26fcf0b7f5)

When I'm trying to open in Andriod, each time I get this error 

The package at "node_modules/request/request.js" attempted to import the Node standard library module "url".
It failed because the native React runtime does not include the Node standard library.

Even if I resolved this, it'll give the same error for other standard modules like path, http

Can you help me on this? I've followed the README but got no luck

I'm using node v16.19.0 and expo 6.3.10

**Comment by nklomp** [comment]
Could you test with the latest develop branch. Do note that you will need node 18 now instead of 16?

**Comment by nklomp** [comment]
Closing as we received no feedback
