### ISSUE TITLE
Required Node version?

### ISSUE THREAD

**Issue by dmitrizagidulin** [Sphereon-Opensource/ssi-mobile-wallet#45]
Hi all,
the README currently requires Node 14 to build the wallet. However, using 14 gives the following error on `yarn install`:

```
error @sphereon/did-auth-siop@0.3.0-unstable.9: The engine "node" is incompatible with this module. 
Expected version ">=16". Got "14.19.0"
error Found incompatible module.
```

Is this ignore-able, or has the required version shifted to 16?

**Comment by nklomp** [comment]
Hi @dmitrizagidulin Yeah sorry about the confusion. We moved to version 16 but the README is pretty explicit about not using version 16 🤷 

You should be able to ignore it, but I suggest to use v16 as we soon will have an  updated version that will for sure need at least v16. The README is updated in the https://github.com/Sphereon-Opensource/ssi-mobile-wallet/tree/feature/VDX-165_siop branch
