### ISSUE TITLE
[ios] share flow: send button is always disabled

### ISSUE THREAD

**Issue by siacomuzzi** [Sphereon-Opensource/ssi-mobile-wallet#80]
Hi, I'm trying the share/presentation flow using the `develop` branch in iOS, but I'm stuck in the following screen because the "Send" button is always disabled:

<img width="300" src="https://user-images.githubusercontent.com/178506/233970823-e0f41993-1c10-43f7-8119-87d2c93126e6.png">

Am I missing something?
Thank you!

**Comment by nklomp** [comment]
Oh that is interesting. We know there are some issues with selecting credentials when there is an icon. The flow is that you should select the 1 list item. Probably, the hitbox is very small because it is named '1' in your example.

Could you try to tap '1' and see whether you go to a selection screen?

Let me see if I can post a video in a few minutes about what should happen.

@BtencateSphereon do you have any other insights to add?

**Comment by siacomuzzi** [comment]
The credential is selected:

<img width="250" src="https://user-images.githubusercontent.com/178506/233974487-a99e5c6a-709d-4dae-b41a-f6ed45e5659b.png"> <img width="250" src="https://user-images.githubusercontent.com/178506/233974077-15a3190a-f558-482e-87aa-52cf7e07caf1.png"> <img width="250" src="https://user-images.githubusercontent.com/178506/233974339-9ca71d95-a144-40dc-a3ab-1301a463363e.png">

BTW, I'm using the Resident Card sample available in https://launchpad.mattrlabs.com/

**Comment by nklomp** [comment]
Oh that is interesting. Thanks we will for sure test that one

**Comment by nklomp** [comment]
Oh that is a really straight forward one.

One last thing that comes to mind. Did you use the back button after the credential selection to go to the initial overview screen. In other words, this you use the Accept button at the button or not? 
Currently the back button does not persist the changes from the screen.

**Comment by siacomuzzi** [comment]
I'm using the "Accept" button after select the credential.

**Comment by siacomuzzi** [comment]
It has to be something related to the credential I'm using... Because when using the default credential (`SphereonWalletIdentityCredential`), the "Send" button is enabled:

<img width="300" src="https://user-images.githubusercontent.com/178506/233986478-4af4c037-6364-4524-901c-70492a9d9ce9.png">

**Comment by nklomp** [comment]
Thank will test it later today with the definition and the Mattr credential.

**Comment by nklomp** [comment]
Okay it seems that Mattr credential doesn't have an id. A VC is optional, but it seems our code does slightly depend on it, so will have to do some fixes

**Comment by nklomp** [comment]
We internally store the VCs (and optionally VPs) with a hash. However we did not re-use these hashes when showing them in the UI. We relied on ids in the VCs, which do not always have to be present.

We are working on a universal rendering component, so this part has always been shaky, given we are going to replace it. But it now has bitten us in the behind ;)

Moved to using hashes only

**Comment by siacomuzzi** [comment]
Now,  the `Accept` button is disabled here:

<img width="300" src="https://user-images.githubusercontent.com/178506/235009733-41b22eae-656a-41a4-915d-7206b0ae6f82.png">

This is my presentation request:

```
{
  "id": "00000000-0000-0000-0000-000000000000",
  "input_descriptors": [
    {
      "id": "1",
      "name": "A specific type of VC",
      "purpose": "We want a VC of this type",
      "schema": [
        {
          "uri": "PermanentResidentCard"
        }
      ]
    }
  ]
}
```

The VC was issued by https://launchpad.mattrlabs.com/

**Comment by siacomuzzi** [comment]
If I enter to the VC details screen and click on the `Select` button, then the `Accept` button is enabled:

<img width="250" src="https://user-images.githubusercontent.com/178506/235011760-c6413436-9576-4a29-99ce-f49479223d6a.png"> <img width="250" src="https://user-images.githubusercontent.com/178506/235011831-a8cda862-b00d-41ef-bc53-1406140c12a7.png">

The issue happens when you select the VC directly using the checkbox element (without going to the details screen):

<img width="84" alt="image" src="https://user-images.githubusercontent.com/178506/235012021-2d2f7c6a-2a16-43ac-804e-8eba9f8b4222.png">

**Comment by nklomp** [comment]
Thanks it is a known issue, which we will solve shortly

**Comment by nklomp** [comment]
This checkbox issue has been fixed in latest develop
